version: '3.6'

services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    networks:
      - overlay1
    ports:
      - 2181:2181
    volumes:
      - /root/zookeeper/data:/data
      - /root/zookeeper/datalog:/datalog
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == Icloud_159]
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    healthcheck:
      test: ["CMD-SHELL","zkServer.sh","status || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3

  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    networks:
      - overlay1
    ports:
      - 2182:2181
    volumes:
      - /root/zookeeper/data:/data
      - /root/zookeeper/datalog:/datalog
    depends_on:
      - zoo1
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == Icloud_158]
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 2
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    healthcheck:
      test: ["CMD-SHELL","zkServer.sh","status || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3


  zoo3:
    image: zookeeper
    restart: always
    networks:
      - overlay1
    hostname: zoo3
    ports:
      - 2183:2181
    volumes:
      - /root/zookeeper/data:/data
      - /root/zookeeper/datalog:/datalog
    depends_on:
      - zoo1
      - zoo2
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == Icloud_160]
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 3
      ZOO_PORT: 2181
      JVMFLAGS: -Xms1024m -Xmx1024m
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    healthcheck:
      test: ["CMD-SHELL","zkServer.sh","status || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3

networks:
  overlay1:
    external: true
    name: overlay1